# Generated by Django 5.1.7 on 2025-04-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent",
                    models.CharField(max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("currency", models.CharField(default="usd", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("job_offer_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("match_score", models.IntegerField(default=0)),
                ("suggestions", models.TextField(blank=True)),
                (
                    "optimized_resume_1",
                    models.FileField(
                        blank=True, null=True, upload_to="optimized_resumes/"
                    ),
                ),
                (
                    "optimized_resume_2",
                    models.FileField(
                        blank=True, null=True, upload_to="optimized_resumes/"
                    ),
                ),
                (
                    "optimized_resume_1_docx",
                    models.FileField(
                        blank=True, null=True, upload_to="optimized_resumes/"
                    ),
                ),
                (
                    "optimized_resume_2_docx",
                    models.FileField(
                        blank=True, null=True, upload_to="optimized_resumes/"
                    ),
                ),
                (
                    "plan_used",
                    models.CharField(
                        choices=[("Free", "Free"), ("Premium", "Premium")],
                        default="Free",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("Free", "Free"), ("Premium", "Premium")],
                        default="Free",
                        max_length=20,
                    ),
                ),
                ("subscription_date", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
