# Generated by Django 5.1.7 on 2025-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeoptimization",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resumeoptimization",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="resumeoptimization",
            name="match_score",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="resumeoptimization",
            name="plan_used",
            field=models.CharField(
                choices=[("Free", "Free"), ("Premium", "Premium")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="resumeoptimization",
            name="suggestions",
            field=models.TextField(),
        ),
    ]
