# Generated by Django 5.1.7 on 2025-04-17 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_resumeoptimization_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeoptimization",
            name="optimized_resume_2",
        ),
        migrations.RemoveField(
            model_name="resumeoptimization",
            name="optimized_resume_2_docx",
        ),
    ]
